version: 2.0
references:
  triggerable-by-tag: &triggerable-by-tag
    # For a tag push unaffected by any filters, CircleCI skips the job
    # https://circleci.com/docs/2.0/workflows/#git-tag-job-execution
    filters:
      tags:
        only: /.*/
  container: &container
    docker:
      - image: circleci/node:10.20.1
  container-browsers: &container-browsers
    docker:
      - image: circleci/node:10.20.1-browsers
  workspace: &workspace
    attach_workspace:
      at: ~/project
  persist: &persist
    persist_to_workspace:
      root: .
      paths:
        - .

jobs:
  checkout_code:
    <<: *container
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
      - run: if [ ! -d "node_modules" ]; then npm install --no-package-lock; fi
      - save_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - *persist

  build:
    <<: *container
    steps:
      - *workspace
      - run: make build
      - *persist
  lint:
    <<: *container
    steps:
      - *workspace
      - run: make lint-ci

  typecheck:
    <<: *container
    steps:
      - *workspace
      - run: make typecheck

  test:
    <<: *container
    steps:
      - *workspace
      - run: make coverage


  nodefetch2:
    <<: *container
    steps:
      - *workspace
      - run: FETCH_MOCK_SRC=../cjs/server.js make test

  nodefetch1:
    <<: *container
    steps:
      - *workspace
      - run: npm install node-fetch@1
      - run: FETCH_MOCK_SRC=../cjs/server.js make test

  node6:
    docker:
      - image: circleci/node:6.13.0
    steps:
      - *workspace
      - run: npm rebuild
      - run: make test-node6

  chrome:
    <<: *container-browsers
    steps:
      - *workspace
      - run: TEST_BROWSER=Chrome make test-browser

  firefox:
    <<: *container-browsers
    steps:
      - *workspace
      - run: npm install karma-firefox-launcher
      - run: TEST_BROWSER=Firefox make test-browser


  deploy:
    <<: *container
    steps:
      - *workspace
      - run: make publish


workflows:
  version: 2
  fetch-mock-ci-cd:
    jobs:
      - checkout_code: *triggerable-by-tag
      - test:
          <<: *triggerable-by-tag
          requires:
            - checkout_code
      - nodefetch1:
          <<: *triggerable-by-tag
          requires:
            - build
      - nodefetch2:
          <<: *triggerable-by-tag
          requires:
            - build
      - node6:
          <<: *triggerable-by-tag
          requires:
            - build
      - chrome:
          <<: *triggerable-by-tag
          requires:
            - build
# firefox version too old for sw, so postpone cross browser tests till updated in circleci
#      - firefox:
#          requires:
#            - checkout_code
      - typecheck:
          <<: *triggerable-by-tag
          requires:
            - checkout_code
      - lint:
          <<: *triggerable-by-tag
          requires:
            - checkout_code
      - build:
          <<: *triggerable-by-tag
          requires:
            - lint
            - test
      - deploy:
          context: wheresrhys-npm-publish
          requires:
            - nodefetch1
            - nodefetch2
            - node6
            - chrome
            - firefox
            - build
            - typecheck
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?\d+\.\d+\.\d+(?:-(beta|alpha)\.\d+)?$/
